### PR TITLE
Adding a geopandas writer

### PR DESCRIPTION
**Pull request by jbeezley**
Ping @mgrauer

### CODE REVIEW

**Comment by aashish24** [comment]
LGTM but someone else should test.

**Comment by mgrauer** [comment]
LGTM.  Tests ran and a client script worked.  Very nice.

**Comment by mgrauer** [comment]
@jbeezley did you want to add geopandas to setup.py?

**Comment by jbeezley** [comment]
I'll pull out my update to requirements.txt and make a new PR for that.

**Pull request merged**
