### PR TITLE
Revamping requirements and optionals

### PR DESCRIPTION
**Pull request by jbeezley**
This addresses #17 as well as a few other issues

 * use a new (post 6.0) feature of pip allowing requirements entries conditioned on python version
 * parse comments in the requirements file to setup extras in setup.py
 * add testing of setup.py
 * remove coverage level test from ctest in favor of coveralls reporting

### CODE REVIEW

**Comment by aashish24** [comment]
:+1:  Worked for me but it would be nice if someone can try it on a machine that didn't have geopandas deps

**Comment by jbeezley** [comment]
That will be possible through `pip install gaia`, which is how I envision most users installing.  The requirements files are mostly for developers.

**Comment by mgrauer** [comment]
I'll test it on a fresh VM using

pip install git+https://github.com/OpenGeoscience/gaia.git@geopandas-requirement

I can probably speed this (testing an install via setup.py with a certain environment) up in the future with some Docker work.

**Comment by aashish24** [comment]
that would be great!!

**Comment by mgrauer** [comment]
Worked for me without the optional requirements.

From a base U14.04 image (mostly for my own records)

    1. sudo apt-get update
    2. sudo apt-get install git
    3. curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    4. sudo python get-pip.py
    5. sudo pip install git+https://github.com/OpenGeoscience/gaia.git@geopandas-requirement
    python --version => Python 2.7.6
    pip --version => pip 6.1.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
    python -c "import gaia; print(gaia.__version__)" => 0.0.1a1

I then tried with the optional requirements.

    6. sudo pip uninstall gaia
    7. sudo apt-get install -y libfreetype6-dev libpng12-dev libgdal-dev
    8. sudo pip install "git+https://github.com/OpenGeoscience/gaia.git@geopandas-requirement#egg=gaia[pandas,esgf]"

This last line failed.

    9. sudo pip install "git+https://github.com/OpenGeoscience/gaia.git@geopandas-requirement#egg=gaia[esgf]"

succeeded.

    10. sudo pip install "git+https://github.com/OpenGeoscience/gaia.git@geopandas-requirement#egg=gaia[pandas]"

failed with

    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

I don't recall installing `python-dev` earlier when I installed all requirements via `sudo pip install -r requirements.txt`.

    11. sudo apt-get install -y python-dev g++
    12. sudo pip install "git+https://github.com/OpenGeoscience/gaia.git@geopandas-requirement#egg=gaia[pandas]"
    python -c "import gaia; print(gaia.__version__)" => 0.0.1a1

**Comment by jbeezley** [comment]
Interesting.  Maybe issuing the requirements through setup.py prevents installing binary packages for some reason?  I've never tried to distribute a python binary extension, so I'm not sure how that works.

**Comment by jbeezley** [comment]
That's kind of annoying that it responds for each build.  I'm just going to enable coveralls status reporting from now on.

**Pull request merged**
